In [12]:
from keras.models import load_model
import time
import numpy as np
import cv2
#import nframe as nf
from PIL import Image
from numpy.matlib import repmat
import math
%matplotlib inline

In [13]:
import math

def msf(numero):
    parte_decimal, parte_entera = math.modf(numero)
    decimal = 100*(round(parte_decimal,3))
    frame = (parte_entera*60+decimal)*30
    return frame

msf(2.43)

4890.0

In [15]:
import math 
#Funcion que retorna la cantidad de segundos en un intervalo
def segs (inicio_video, final_video):
    decimal_inicial, entero_inicio = math.modf(inicio_video) 
    decimal_final, entero_final = math.modf(final_video) 
    decimal_inicial =  100*(round(decimal_inicial,3))
    decimal_final =  100*(round(decimal_final,3))

    ef = entero_final
    ei = entero_inicio
    df = decimal_final
    di = decimal_inicial
    
    segs = 60*(ef-ei) + (df-di)
    return int(segs)

segs(3,4)

60

In [3]:
#Cargar modelo
model = load_model('model_1C128N0.5DROPBATCH64, \n
20Ssteps35epochs_data2.2.1.h5')

In [4]:
#Declaración de variables 
videopath = 'DataSernapesca//Con Bacterias//120124//13-03-2019//T1.avi'
cap = cv2.VideoCapture(videopath)
fps = cap.get(cv2.CAP_PROP_FPS)
cont = 1
cont1 = 0
inicio_video = 3.50
final_video = 9.45
seg = segs(inicio_video, final_video)
fpsextr = 3
a = np.zeros((seg*fpsextr, 224,224,3))
print(seg)

355


In [5]:
tiempos = []
now = time.time()
while cap.isOpened():
    ret, frame = cap.read()
    
    if ret == False:
        break
        
    if(msf(inicio_video) <= cont <= msf(final_video)):
        if(cont%(30//fpsextr) == 0):
            image = np.array(frame)
            image.resize(1,224,224,3)
            
            if (cont1 < seg*fpsextr):
                a[cont1,:,:,:] = image
                cont1+=1
            
            elif (cont1 == seg*fpsextr):
                cont1 = 0
    
            duration = cont/fps
            minutes = int(duration/60)
            seconds = int(duration%60)
            tiempos.append(str(minutes) + ':' + str(seconds))
    
    cont = cont+1         
    
    if (cont == (msf(final_video)+1)):
        break
cap.release

print(f'Duración evaluación del video :\n
      {(time.time()-now)/60} Minutos Aprox.')

Duración evaluación del video : 2.3112370570500693 Minutos Aprox.


In [28]:
print(a)
print(a.shape)

[[[[  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]
   ...
   [ 71. 101. 106.]
   [ 71. 101. 106.]
   [ 71. 101. 106.]]

  [[ 69. 100. 107.]
   [ 69. 100. 107.]
   [ 71. 101. 106.]
   ...
   [ 75.  87.  84.]
   [ 77.  89.  88.]
   [ 80.  92.  91.]]

  [[ 86.  97.  98.]
   [ 85.  96.  97.]
   [ 85. 101. 101.]
   ...
   [ 79.  82.  82.]
   [ 83.  83.  83.]
   [ 83.  83.  83.]]

  ...

  [[ 78.  81.  79.]
   [ 78.  81.  79.]
   [ 77.  80.  78.]
   ...
   [ 97. 101. 103.]
   [ 96. 100. 102.]
   [ 99. 103. 105.]]

  [[ 90. 105. 103.]
   [ 90. 105. 103.]
   [ 96. 104. 103.]
   ...
   [ 56.  59.  64.]
   [ 53.  56.  61.]
   [ 68.  71.  76.]]

  [[ 60.  84.  81.]
   [ 62.  86.  83.]
   [120. 140. 135.]
   ...
   [ 81. 112. 109.]
   [ 84. 111. 112.]
   [ 80. 107. 108.]]]


 [[[  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]
   ...
   [ 81. 110. 119.]
   [ 81. 108. 115.]
   [ 81. 108. 115.]]

  [[ 94. 108. 113.]
   [ 88. 102. 107.]
   [ 86. 100. 105.]
   ...
   [ 77.  89.  88.]
 

In [27]:
print(tiempos)

['3:50', '3:50', '3:50', '3:51', '3:51', '3:51', '3:52', '3:52', '3:52', '3:53', '3:53', '3:53', '3:54', '3:54', '3:54', '3:55', '3:55', '3:55', '3:56', '3:56', '3:56', '3:57', '3:57', '3:57', '3:58', '3:58', '3:58', '3:59', '3:59', '3:59', '4:0', '4:0', '4:0', '4:1', '4:1', '4:1', '4:2', '4:2', '4:2', '4:3', '4:3', '4:3', '4:4', '4:4', '4:4', '4:5', '4:5', '4:5', '4:6', '4:6', '4:6', '4:7', '4:7', '4:7', '4:8', '4:8', '4:8', '4:9', '4:9', '4:9', '4:10', '4:10', '4:10', '4:11', '4:11', '4:11', '4:12', '4:12', '4:12', '4:13', '4:13', '4:13', '4:14', '4:14', '4:14', '4:15', '4:15', '4:15', '4:16', '4:16', '4:16', '4:17', '4:17', '4:17', '4:18', '4:18', '4:18', '4:19', '4:19', '4:19', '4:20', '4:20', '4:20', '4:21', '4:21', '4:21', '4:22', '4:22', '4:22', '4:23', '4:23', '4:23', '4:24', '4:24', '4:24', '4:25', '4:25', '4:25', '4:26', '4:26', '4:26', '4:27', '4:27', '4:27', '4:28', '4:28', '4:28', '4:29', '4:29', '4:29', '4:30', '4:30', '4:30', '4:31', '4:31', '4:31', '4:32', '4:32', '4:32

In [6]:
now = time.time()
result = model.predict(a)
print(f'Duración predicción de las imágenes :\n
{(time.time()-now)/60} Minutos Aprox.')

Duración predicción de las imágenes : 6.039960829416911 Minutos Aprox.


In [18]:
result[:10]

array([[0.0985373 ],
       [0.04983395],
       [0.05266756],
       [0.04749817],
       [0.3712685 ],
       [0.97166693],
       [0.9844668 ],
       [0.95048326],
       [0.7153778 ],
       [0.98995745]], dtype=float32)

In [40]:
#Resultados bacterias sobre 0.5
resultados_b = (result>0.5)*1

In [41]:
resultados_b[:10]

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1]])

In [42]:
frec_intervalo = 10
tomador_decision = 2

resultados_f = np.zeros(resultados_b.shape[0]-frec_intervalo)

for i in range (0, resultados_b.shape[0]-frec_intervalo, 1):
    temp = resultados_b[i:i+frec_intervalo]
    resultados_f[i] = temp.sum() > tomador_decision

print(f'Intervalos de tiempo con bacterias :\n
{((resultados_f == 1)*1).sum()}')

print(f'Intervalos de tiempo sin bacterias :\n
{((resultados_f == 0)*1).sum()}')

Intervalos de tiempo con bacterias : 191
Intervalos de tiempo sin bacterias : 864


In [43]:
resultados_f

array([0., 1., 1., ..., 0., 0., 0.])

In [44]:
intervalos = []
i = 0 
while (i < resultados_f.shape[0]):
    if resultados_f[i] == 1:
        inic = i
        i+=1    
            
        while resultados_f[i] == 1:
                i+=1
                if i == resultados_f.shape[0]:
                    break 
        fin = i-1
        intervalos.append((inic,fin))
    
    i+=1
print(intervalos)

[(1, 10), (124, 124), (147, 152), (182, 183), (186, 188), (254, 303), (310, 326), (402, 414), (421, 438), (494, 505), (526, 536), (643, 645), (674, 681), (719, 729), (900, 925)]


In [45]:
for n in range (0, len(intervalos)):
    print(f'duración\n
:{tiempos[intervalos[n][0]]}-{tiempos[intervalos[n][1]]}')

duración 3:50  -  3:53
duración 4:31  -  4:31
duración 4:39  -  4:40
duración 4:50  -  4:51
duración 4:52  -  4:52
duración 5:14  -  5:31
duración 5:33  -  5:38
duración 6:4  -  6:8
duración 6:10  -  6:16
duración 6:34  -  6:38
duración 6:45  -  6:48
duración 7:24  -  7:25
duración 7:34  -  7:37
duración 7:49  -  7:53
duración 8:50  -  8:58
